# Generated by Django 3.2.7 on 2021-09-20 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20210920_0508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product',
            new_name='item',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='orderproducts',
            new_name='orderitems',
        ),
    ]
